---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

permissions:
  contents: write

jobs:
  workflows:
    uses: stevusprimus/hassio-addons-workflows/.github/workflows/addon-ci.yaml@main
